// Real data extracted from FORUM2026_MASTER.xlsx

export const ASSOCIATIONS = [
  { n: 1, name: 'I Mua Papeete', discipline: 'Natation', sites: ['Faaa','Punaauia','Arue'], prio: 'A', hist: [2020,2023,2024,2025], contact: 'TAUMIHAU-GATIEN Tinihau', tel: '89 40 22 04', email: 'swimua.tahiti@gmail.com', animation: 'Vidéo sur stand' },
  { n: 2, name: 'Olympique de Pirae', discipline: 'Natation / Sauvetage', sites: ['Faaa','Punaauia','Arue'], prio: 'A', hist: [2020,2023,2024], contact: 'TAPI Romy', tel: '87 76 44 10', email: 'olpnatation@gmail.com', animation: 'Vidéo sur stand' },
  { n: 3, name: 'Ecole Judo de Polynésie', discipline: 'Judo', sites: ['Faaa','Punaauia','Arue'], prio: 'A', hist: [2020,2023], contact: 'BERTRAND Arnaud', tel: '87 75 98 68', email: 'arnaudtahiti@gmail.com', animation: 'Démonstration' },
  { n: 4, name: 'Polyné livre', discipline: 'Lecture / Dons livres', sites: ['Punaauia','Arue','Taravao'], prio: 'A', hist: [2020,2023,2024], contact: 'AUBINEAU Janick', tel: '89 76 23 77', email: 'aubineaujanick@gmail.com', animation: 'Séance de lecture' },
  { n: 5, name: 'Tefana Judo', discipline: 'Judo / MMA', sites: ['Faaa','Arue'], prio: 'A', hist: [2020,2023], contact: 'TIVANT Nicolas', tel: '87 77 07 90', email: 'tefanajudo@gmail.com', animation: 'Démonstration' },
  { n: 6, name: "Varuatahi Va'a Tahiti", discipline: "Va'a", sites: ['Faaa','Punaauia','Arue'], prio: 'B', hist: [2020], contact: 'PAIE ELLIS Stanley', tel: '89 40 03 03', email: 'varuatahiti@gmail.com', animation: 'Stand' },
  { n: 7, name: 'Judo Club de Taravao', discipline: 'Judo', sites: ['Faaa','Arue','Taravao'], prio: 'A', hist: [2020,2023,2024,2025], contact: 'DELANNE Cédric', tel: '87 74 64 06', email: 'cedricdelanne9@hotmail.com', animation: 'Démonstration' },
  { n: 8, name: 'Pilates Studio Tahiti', discipline: 'Pilates', sites: ['Faaa','Punaauia'], prio: 'B', hist: [2020], contact: 'LEMONNIER Joëlle', tel: '87 38 74 18', email: 'joylemon19@gmail.com', animation: 'Démonstrations' },
  { n: 9, name: 'Hapkido JJK Tahiti', discipline: 'Judo', sites: ['Faaa','Arue'], prio: 'B', hist: [2020], contact: 'CHEONG Jean-Marc', tel: '89 71 53 30', email: 'hapkidojjktahiti@gmail.com', animation: 'Démonstration' },
  { n: 10, name: 'Dream Lab', discipline: 'Musique', sites: ['Faaa','Punaauia','Arue','Taravao'], prio: 'B', hist: [2020], contact: 'MORGAN Tuhina', tel: '87 75 75 40', email: 'tuhina.morgan@gmail.com', animation: 'Démonstrations' },
  { n: 11, name: 'Tahiti English School', discipline: 'Langue anglaise', sites: ['Arue','Taravao'], prio: 'A', hist: [2020,2023,2024,2025], contact: 'BOVE Johanna', tel: '89 72 24 80', email: 'tahitienglishschool@gmail.com', animation: "Atelier d'anglais" },
  { n: 12, name: 'Budokan Judo Pirae', discipline: 'Judo / Kendo', sites: ['Arue'], prio: 'A', hist: [2020,2023,2024], contact: 'NICOLLIN Lavaïna', tel: '87 30 97 20', email: 'budokanjudopirae@gmail.com', animation: 'Vidéo sur stand' },
  { n: 13, name: 'Tefana Taekwondo', discipline: 'Taekwondo', sites: ['Faaa'], prio: 'A', hist: [2020,2023,2024], contact: 'TAVITA Nathalie', tel: '89 40 20 20', email: 'tefanataekwondo@gmail.com', animation: 'Démonstration' },
  { n: 14, name: 'Centre danse André Tschan', discipline: 'Danse', sites: ['Faaa','Arue'], prio: 'A', hist: [2020,2023,2024,2025], contact: 'TSCHAN André', tel: '40 41 20 04', email: 'centrededanse.tschan@gmail.com', animation: 'Barre de danse / Démo' },
  { n: 15, name: 'Etuahi Ori Tahiti', discipline: 'Ori Tahiti / Danse feu', sites: ['Faaa'], prio: 'A', hist: [2020,2023], contact: 'ONDICOLDBERRY Tamatea', tel: '87 32 52 00', email: 'etuahi.oritane@gmail.com', animation: 'Spectacle Ven 15h / Sam 10h+16h' },
  { n: 16, name: 'Tauariki Ori Tahiti', discipline: 'Ori Tahiti', sites: ['Faaa'], prio: 'B', hist: [2020], contact: null, tel: null, email: 'tauariki.oritahiti@hotmail.com', animation: 'Spectacle Sam 10h30' },
  { n: 17, name: 'Académie danse Annie Fayn', discipline: 'Danse', sites: ['Faaa'], prio: 'B', hist: [2020], contact: 'FAYN Annie', tel: '40 41 20 04', email: 'academiededanseanniefayn@gmail.com', animation: 'Chorégraphie et vidéo' },
  { n: 18, name: 'Atelier Robots Lego', discipline: 'Robotique', sites: ['Faaa'], prio: 'B', hist: [2020], contact: 'GEIRNAERT Thierry', tel: '89 67 00 00', email: 't.geirnaert@hotmail.com', animation: 'Défilé de robots' },
  { n: 19, name: '3TBC', discipline: 'Boxe anglaise', sites: ['Faaa','Arue'], prio: 'B', hist: [2020], contact: null, tel: null, email: null, animation: 'Démonstration' },
  { n: 20, name: 'Ludo Maths Fenua', discipline: 'Robotique / Soutien', sites: ['Faaa','Punaauia'], prio: 'C', hist: [2020], contact: null, tel: null, email: null, animation: 'Stand' },
  { n: 21, name: 'Tahiti Pol Art', discipline: 'Art', sites: ['Faaa'], prio: 'C', hist: [2020], contact: 'MAHINUI Vaiana', tel: '87 79 85 15', email: 'tahitipoleart@gmail.com', animation: 'Stand' },
  { n: 22, name: 'Eleuthera Tahiti', discipline: 'Plongée / Permis bateau', sites: ['Punaauia'], prio: 'A', hist: [2020,2023,2024], contact: 'CASTEL Nicolas', tel: '87 77 65 68', email: 'contact@eleutheratahiti.com', animation: 'Simulation bouteilles' },
  { n: 23, name: 'Punaauia Judo Jujitsu', discipline: 'Judo / Jujitsu', sites: ['Punaauia'], prio: 'A', hist: [2020,2023,2024], contact: 'VERNAUDON Rauhiti', tel: '87 21 95 76', email: 'jcpunaauia@gmail.com', animation: 'Démonstration' },
  { n: 24, name: 'Taina Natation', discipline: 'Natation', sites: ['Punaauia','Taravao'], prio: 'A', hist: [2020,2023,2024,2025], contact: 'DELAFOUILHOUZE Jean-Louis', tel: '87 78 11 27', email: 'tainanatation@mail.pf', animation: 'Écran vidéo' },
  { n: 25, name: 'Fenua Sauvetage Natation', discipline: 'Natation / Sauvetage', sites: ['Punaauia'], prio: 'A', hist: [2020,2023,2024], contact: 'SCHUFT Moana', tel: '89 25 34 19', email: 'fenuasauvetagenatation@gmail.com', animation: 'Écran vidéo' },
  { n: 26, name: 'AS Manu Ura', discipline: 'Judo', sites: ['Punaauia'], prio: 'B', hist: [2020], contact: null, tel: null, email: null, animation: 'Démonstration' },
  { n: 27, name: 'Punaauia Rugby Club', discipline: 'Rugby', sites: ['Punaauia'], prio: 'B', hist: [2020,2023], contact: null, tel: null, email: 'decographic@mail.pf', animation: 'Démonstration' },
  { n: 28, name: 'Centre danse Vanessa Roche', discipline: 'Danse / Bien-être', sites: ['Punaauia'], prio: 'B', hist: [2020], contact: 'ROCHE Vanessa', tel: '87 22 45 93', email: 'centrededanse@vanessaroche.com', animation: 'Stand' },
  { n: 29, name: 'Fédération PF Escrime', discipline: 'Escrime', sites: ['Punaauia'], prio: 'A', hist: [2020,2023], contact: 'BELLANGER Arnaud', tel: '89 32 99 78', email: 'arnaud.bellanger34@gmail.com', animation: 'Démonstrations' },
  { n: 30, name: 'Polykids', discipline: 'Jeux vidéo / Ateliers', sites: ['Punaauia'], prio: 'C', hist: [2020], contact: null, tel: null, email: null, animation: 'Stand' },
  { n: 31, name: 'ACE Arue', discipline: 'Athlétisme', sites: ['Arue'], prio: 'A', hist: [2020,2023,2024], contact: 'LE PRINCE Serge', tel: '89 78 91 14', email: 'lpeserge@gmail.com', animation: 'Vidéo stand' },
  { n: 32, name: 'Lotus Bleu', discipline: 'Langue chinoise', sites: ['Arue'], prio: 'A', hist: [2020,2023,2024], contact: 'LI Niannian', tel: '87 30 36 66', email: 'lotusbleu.tahiti@gmail.com', animation: 'Atelier chinois' },
  { n: 33, name: 'AS JT (Jeunes Tahitiens)', discipline: 'Multisports', sites: ['Arue'], prio: 'B', hist: [2020], contact: null, tel: null, email: null, animation: 'Démonstration' },
  { n: 34, name: 'Riding Team Tahiti', discipline: 'Cyclisme / BMX', sites: ['Arue'], prio: 'B', hist: [2020], contact: 'CHONFON Heimata', tel: '87 77 91 16', email: 'ridineteamtahiti@gmail.com', animation: 'Stand' },
  { n: 35, name: 'Cercle Nageurs de PF', discipline: 'Natation', sites: ['Arue'], prio: 'B', hist: [2020], contact: 'CAPPARELLI Alexandre', tel: '87 78 72 28', email: 'resp-natation-course@cn-polynesie.com', animation: 'Stand' },
  { n: 36, name: "Fines Lames d'Arue", discipline: 'Escrime', sites: ['Arue'], prio: 'C', hist: [2020], contact: null, tel: null, email: null, animation: 'Démonstration' },
  { n: 37, name: 'Excelsior Taekwondo', discipline: 'Taekwondo', sites: ['Arue'], prio: 'C', hist: [2020], contact: null, tel: null, email: null, animation: 'Démonstration' },
  { n: 38, name: 'Soleil Levant', discipline: 'Cours de japonais', sites: ['Arue'], prio: 'C', hist: [2020], contact: null, tel: null, email: 'soleil.levant.nihongo@gmail.com', animation: 'Stand' },
  { n: 39, name: 'ADAT', discipline: 'Athlétisme', sites: ['Taravao'], prio: 'A', hist: [2020,2023,2024], contact: 'AUBINEAU Janick', tel: '89 76 23 77', email: 'aubineaujanick@gmail.com', animation: 'Vidéo stand' },
  { n: 40, name: 'Monoihere', discipline: 'Danse Polynésienne', sites: ['Taravao'], prio: 'A', hist: [2020,2023,2024], contact: 'ALEXANDRE Augustin', tel: '87 30 17 83', email: 'monoihereoritahiti@gmail.com', animation: 'Spectacle Sam 11h' },
  { n: 41, name: 'Centre Nautique Baie Phaeton', discipline: 'Voile', sites: ['Taravao'], prio: 'A', hist: [2020,2023,2024], contact: 'DE PREVILLE Gilles', tel: '87 75 70 11', email: 'cnbp@outlook.fr', animation: 'Vidéo stand' },
  { n: 42, name: 'English Club de Taravao', discipline: 'Anglais / Dessin', sites: ['Taravao'], prio: 'B', hist: [2020], contact: null, tel: null, email: null, animation: 'Atelier anglais + Dessin' },
  { n: 43, name: 'Club Karaté de Taravao', discipline: 'Karaté', sites: ['Taravao'], prio: 'B', hist: [2020], contact: null, tel: null, email: null, animation: 'Démo Sam 13h' },
  { n: 44, name: "Taravao Basket Toroz's", discipline: 'Basket-ball', sites: ['Taravao'], prio: 'B', hist: [2020], contact: null, tel: null, email: null, animation: 'Démonstration' },
  { n: 45, name: 'Tahitian Martial Spirit', discipline: 'Taekwondo / Jujitsu', sites: ['Taravao'], prio: 'B', hist: [2020], contact: null, tel: null, email: null, animation: 'Démonstration' },
  { n: 46, name: 'Atelier des Lumières', discipline: 'Soutien scolaire', sites: ['Taravao'], prio: 'B', hist: [2020], contact: null, tel: null, email: null, animation: 'Vidéo stand' },
  { n: 47, name: 'Tahiti Iti Natation', discipline: 'Natation / Sauvetage', sites: ['Taravao'], prio: 'B', hist: [2020], contact: null, tel: null, email: null, animation: 'Vidéo stand' },
  { n: 48, name: 'Origami Art Tahiti Iti', discipline: 'Origami / Art / Japonais', sites: ['Taravao'], prio: 'B', hist: [2020], contact: 'EGUCHI Aya', tel: '87 28 11 98', email: 'eguchiaya@gmail.com', animation: 'Stand' },
  { n: 49, name: 'Anset Assurances', discipline: 'Assurance', sites: ['Taravao'], prio: 'B', hist: [2020], contact: 'COTTANCEAU Christelle', tel: '40 50 93 50', email: 'secretariat@anset.pf', animation: 'Stand' },
  { n: 50, name: 'Moeata Ori Tahiti', discipline: 'Ori Tahiti', sites: ['Taravao'], prio: 'B', hist: [2020], contact: 'LAUGHLIN Moeta', tel: '89 78 69 67', email: 'wickylaughlin@gmail.com', animation: 'Stand' },
  { n: 51, name: 'Surf Hitinui', discipline: 'Surf', sites: ['Taravao'], prio: 'B', hist: [2020], contact: 'Doumè', tel: '87 73 14 21', email: 'surfhitinui@gmail.com', animation: 'Vidéo stand' },
  { n: 52, name: 'Danse Vahinerii', discipline: 'Danse', sites: ['Taravao'], prio: 'C', hist: [2020], contact: 'BRODIEN Tuiana', tel: '87 35 64 54', email: 'brodientuiana@gmail.com', animation: 'Stand' },
  { n: 53, name: 'Kids Time Taravao', discipline: 'Activités enfants', sites: ['Taravao'], prio: 'C', hist: [2020], contact: 'ELLACOTT Maeva', tel: '87 29 97 65', email: 'kidstimetaravao@gmail.com', animation: 'Stand' },
  { n: 54, name: 'Dojo Takemusu', discipline: 'Arts martiaux', sites: ['Taravao'], prio: 'C', hist: [2020], contact: 'Xavier', tel: '87 27 81 54', email: 'heitefau@gmail.com', animation: 'Stand' },
  { n: 55, name: 'Chat Pito', discipline: 'Activités enfants', sites: ['Mahina'], prio: 'C', hist: [2020], contact: 'Hildevert', tel: '87 70 60 39', email: 'chatpito.tahiti@gmail.com', animation: 'Stand' },
  { n: 56, name: 'Wind Chasers Tahiti', discipline: 'Kitesurf / Voile', sites: ['Mahina'], prio: 'C', hist: [2020], contact: 'Elise', tel: '89 53 08 14', email: 'windchaserstahiti@gmail.com', animation: 'Stand' },
  { n: 57, name: 'Académie Piano Tahiti', discipline: 'Musique', sites: [], prio: 'prospect', hist: [], contact: null, tel: null, email: 'ecolepianotahiti@gmail.com', animation: 'Stand' },
  { n: 58, name: 'Music Hall de Tahiti', discipline: 'Musique', sites: [], prio: 'prospect', hist: [], contact: null, tel: null, email: 'musichalldetahiti@gmail.com', animation: 'Stand' },
  { n: 59, name: 'Algora Tahiti', discipline: 'Soutien scolaire', sites: [], prio: 'prospect', hist: [], contact: null, tel: null, email: 'algora.tahiti@gmail.com', animation: 'Stand' },
  { n: 60, name: 'Fare Musique', discipline: 'Musique', sites: [], prio: 'prospect', hist: [], contact: null, tel: null, email: 'ecolefaremusique@gmail.com', animation: 'Stand' },
  { n: 61, name: 'Go Baby Gym Tahiti', discipline: 'Éveil sportif bébés', sites: [], prio: 'prospect', hist: [], contact: null, tel: null, email: 'tahiti@gobabygym.com', animation: 'Stand' },
  { n: 62, name: 'AIO Tahiti', discipline: 'Activités', sites: [], prio: 'prospect', hist: [], contact: null, tel: null, email: 'contacts.aiotahiti@gmail.com', animation: 'Stand' },
  { n: 63, name: 'Wushu Style Tahiti', discipline: 'Arts martiaux', sites: [], prio: 'prospect', hist: [], contact: null, tel: null, email: 'wustyletahiti@gmail.com', animation: 'Démonstration' },
  { n: 64, name: 'Les Petits Motu', discipline: 'Activités enfants', sites: [], prio: 'prospect', hist: [], contact: 'Aurore', tel: null, email: 'lepitimotu@gmail.com', animation: 'Stand' },
  { n: 65, name: 'Vaheana School', discipline: 'Éducation', sites: [], prio: 'prospect', hist: [], contact: null, tel: null, email: 'contact@vaheana.school', animation: 'Stand' },
  { n: 66, name: 'Bricolab Tahiti', discipline: 'Fabrication / DIY', sites: [], prio: 'prospect', hist: [], contact: null, tel: null, email: 'bricolab.tahiti@gmail.com', animation: 'Stand' },
];

// Planning stands by site (from PLANNING 2026 sheet) : list of {assoc_n, stand_code, status}
export const PLANNING = [
  // FAAA — F-A01..F-A16
  { site: 'Faaa', rows: [
    { n: 1, stand: 'F-A01', status: 'a_confirmer' },
    { n: 13, stand: 'F-A02', status: 'a_confirmer' },
    { n: 3, stand: 'F-A03', status: 'a_confirmer' },
    { n: 15, stand: 'F-A04', status: 'a_confirmer' },
    { n: 2, stand: 'F-A05', status: 'a_confirmer' },
    { n: 5, stand: 'F-A06', status: 'a_confirmer' },
    { n: 14, stand: 'F-A07', status: 'a_confirmer' },
    { n: 7, stand: 'F-A08', status: 'a_relancer' },
    { n: 17, stand: 'F-A09', status: 'a_relancer' },
    { n: 18, stand: 'F-A10', status: 'a_relancer' },
    { n: 8, stand: 'F-A11', status: 'a_relancer' },
    { n: 9, stand: 'F-A12', status: 'a_relancer' },
    { n: 16, stand: 'F-A13', status: 'a_relancer' },
    { n: 6, stand: 'F-A14', status: 'a_relancer' },
    { n: 19, stand: 'F-A15', status: 'a_relancer' },
    { n: 10, stand: 'F-A16', status: 'a_relancer' },
  ]},
  // PUNAAUIA — P-B01..P-B13
  { site: 'Punaauia', rows: [
    { n: 22, stand: 'P-B01', status: 'a_confirmer' },
    { n: 23, stand: 'P-B02', status: 'a_confirmer' },
    { n: 25, stand: 'P-B03', status: 'a_confirmer' },
    { n: 1, stand: 'P-B04', status: 'a_relancer' },
    { n: 2, stand: 'P-B05', status: 'a_relancer' },
    { n: 24, stand: 'P-B06', status: 'a_relancer' },
    { n: 4, stand: 'P-B07', status: 'a_relancer' },
    { n: 29, stand: 'P-B08', status: 'a_confirmer' },
    { n: 28, stand: 'P-B09', status: 'a_relancer' },
    { n: 26, stand: 'P-B10', status: 'a_relancer' },
    { n: 27, stand: 'P-B11', status: 'a_relancer' },
    { n: 6, stand: 'P-B12', status: 'a_relancer' },
    { n: 10, stand: 'P-B13', status: 'a_relancer' },
  ]},
  // ARUE — A-C01..A-C12
  { site: 'Arue', rows: [
    { n: 1, stand: 'A-C01', status: 'a_relancer' },
    { n: 31, stand: 'A-C02', status: 'a_confirmer' },
    { n: 12, stand: 'A-C03', status: 'a_confirmer' },
    { n: 32, stand: 'A-C04', status: 'a_confirmer' },
    { n: 2, stand: 'A-C05', status: 'a_relancer' },
    { n: 11, stand: 'A-C06', status: 'a_confirmer' },
    { n: 5, stand: 'A-C07', status: 'a_relancer' },
    { n: 3, stand: 'A-C08', status: 'a_relancer' },
    { n: 4, stand: 'A-C09', status: 'a_relancer' },
    { n: 9, stand: 'A-C10', status: 'a_relancer' },
    { n: 34, stand: 'A-C11', status: 'a_relancer' },
    { n: 19, stand: 'A-C12', status: 'a_relancer' },
  ]},
  // TARAVAO — T-D01..T-D12
  { site: 'Taravao', rows: [
    { n: 39, stand: 'T-D01', status: 'a_confirmer' },
    { n: 41, stand: 'T-D02', status: 'a_confirmer' },
    { n: 7, stand: 'T-D03', status: 'a_relancer' },
    { n: 40, stand: 'T-D04', status: 'a_confirmer' },
    { n: 4, stand: 'T-D05', status: 'a_relancer' },
    { n: 42, stand: 'T-D06', status: 'a_relancer' },
    { n: 43, stand: 'T-D07', status: 'a_relancer' },
    { n: 44, stand: 'T-D08', status: 'a_relancer' },
    { n: 48, stand: 'T-D09', status: 'a_relancer' },
    { n: 45, stand: 'T-D10', status: 'a_relancer' },
    { n: 47, stand: 'T-D11', status: 'a_relancer' },
    { n: 46, stand: 'T-D12', status: 'a_relancer' },
  ]},
  // MAHINA — M-E01..M-E07
  { site: 'Mahina', rows: [
    { n: 55, stand: 'M-E01', status: 'a_relancer' },
    { n: 56, stand: 'M-E02', status: 'a_relancer' },
    { n: 1, stand: 'M-E03', status: 'prospect' },
    { n: 59, stand: 'M-E04', status: 'prospect' },
    { n: 61, stand: 'M-E05', status: 'prospect' },
    { n: 62, stand: 'M-E06', status: 'prospect' },
    { n: 63, stand: 'M-E07', status: 'prospect' },
  ]},
  // MOOREA — R-F01..R-F07
  { site: 'Moorea', rows: [
    { n: 1, stand: 'R-F01', status: 'prospect' },
    { n: 4, stand: 'R-F02', status: 'prospect' },
    { n: 58, stand: 'R-F03', status: 'prospect' },
    { n: 60, stand: 'R-F04', status: 'prospect' },
    { n: 57, stand: 'R-F05', status: 'prospect' },
    { n: 64, stand: 'R-F06', status: 'prospect' },
    { n: 66, stand: 'R-F07', status: 'prospect' },
  ]},
];

export const VENUE_INFO = [
  {
    code: 'FAAA', name: 'Faaa', prefix: 'F-A', stand_count: 16, is_available_2026: true,
    owner_sci: 'SCI MANANUI',
    full_address: "Centre Commercial Pacific Faa'a, Faaa, Tahiti",
    convention_pdf_url: 'https://customer-assets.emergentagent.com/job_polynesie-event-hub/artifacts/jqe16q7m_Convention%20mise%20a%CC%80%20dispo%20stand%20-%20RDC26%20Faa%27a.pdf',
  },
  {
    code: 'PUN', name: 'Punaauia', prefix: 'P-B', stand_count: 13, is_available_2026: true,
    owner_sci: 'SCI ATIIO',
    full_address: 'Centre Commercial Pacific Punaauia, Punaauia, Tahiti',
    convention_pdf_url: 'https://customer-assets.emergentagent.com/job_polynesie-event-hub/artifacts/fg5afjjp_Convention%20mise%20a%CC%80%20dispo%20stand%20-%20RDC26%20Puna.pdf',
  },
  {
    code: 'ARU', name: 'Arue', prefix: 'A-C', stand_count: 12, is_available_2026: true,
    owner_sci: 'S.C.I. TAMAHANA',
    full_address: 'Centre Commercial Pacific Arue, Arue, Tahiti',
    convention_pdf_url: 'https://customer-assets.emergentagent.com/job_polynesie-event-hub/artifacts/v1m49kdm_Convention%20mise%20a%CC%80%20dispo%20stand%20-%20RDC26%20Arue.pdf',
  },
  {
    code: 'TAR', name: 'Taravao', prefix: 'T-D', stand_count: 12, is_available_2026: true,
    owner_sci: 'S.C.I. TEMAHAME NUI',
    full_address: "Centre Commercial Pacific Taravao, Taravao, Presqu'île de Tahiti",
    convention_pdf_url: 'https://customer-assets.emergentagent.com/job_polynesie-event-hub/artifacts/u7049h8z_Convention%20mise%20a%CC%80%20dispo%20stand%20-%20RDC26%20TRV.pdf',
  },
  { code: 'MAH', name: 'Mahina', prefix: 'M-E', stand_count: 7, is_available_2026: false, owner_sci: null, full_address: 'Mahina, Tahiti', convention_pdf_url: null },
  { code: 'MOO', name: 'Moorea', prefix: 'R-F', stand_count: 7, is_available_2026: false, owner_sci: null, full_address: 'Moorea', convention_pdf_url: null },
];
